### ISSUE TITLE
There should be a place to show element documentation guides. Guides can be generic, or tied to a product line. Guides will be markdown-based.

### ISSUE THREAD

**Issue by mbleigh** [Polymer/polymer-element-catalog#17]
Let's keep it simple. Guides will be stored as `.md` files in a `guides` folder in the main project. They will have YAML frontmatter (like Jekyll) that contains metadata, starting with `title`, `summary`, `tags`, `updated` (date in form `YYYY-MM-DD`). Let's make a Gulp task that scans the `guides directory and builds metadata to insert into`catalog.json`.
### Example Markdown File (e.g. `bower_components/gold-elements/guides/ecommerce.md`)

``` markdown

---
title: How to Build an E-Commerce Site with Gold Elements
summary: "Learn how to add drop-in E-commerce components to quickly build a web presence for your business."
tags: ['ecommerce','beginner']
elements: ['gold-checkout','paper-input']
updated: 2015-04-10

---

Actual article content starts here.

## Example Section

Etc. etc.
```
### Example `catalog.json`

``` js
{
  // guides with associated packages should also be referenced in the package metadata
  "packages": [
    {"name":"gold-elements","guides":["gold-elements/ecommerce"]}
  ],
  "guides": [
    {
      "name":"gold-elements/ecommerce",
      "title":"How to Build an E-Commerce Site with Gold Elements",
      "tags":["ecommerce","beginner"],
      "elements":["gold-checkout","paper-input"],
      "package":"gold-elements"
    }
  ],
  "elements": [
     {"name":"paper-input","guides":["gold-elements/ecommerce"]}
  ]
}
```
### HTML Generation

In addition to parsing the metadata, the Markdown should be rendered into HTML and output into `.tmp` and `dist` at `guides/<guide-name>.html`
### Guides in Other Repos

Guides can be added to package or individual element repositories as well. When scanning a package or element, the `guides` folder in the bower directory should be scanned as well. If there are any Markdown files, they should be parsed and aggregated but have the `package` or `element` key set in their metadata (depending on if it's a package or element repo you're exploring).

In addition, guides in other repos should have generated HTML placed in subdirectories named after them to avoid name conflicts. So a guide named`my-guide.md` in `iron-elements` should have generated HTML in `app/iron-elements/my-guide.html`.
## Todo
- [x] add guides to `guide` key in catalog.json
- [x] add `guides` array to package listing in catalog.json
- [x] convert markdown to html in `.tmp` and `dist` folders
